# Generated by Django 2.0.2 on 2018-03-01 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_day',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
